version: '3.5'
services:
  selenoid:
    container_name: selenoid
    image: aerokube/selenoid:latest-release
    volumes:
      - ./browsers.json:/etc/selenoid/browsers.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["-conf", "/etc/selenoid/browsers.json", "-limit", "5", "-timeout", "60s", "-container-network", "selenoid"]
    ports:
      - "4444:4444"
    networks:
      selenoid:
        aliases:
          - selenoid.local

  prometheus_metrics:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8800:8800"
    networks:
      selenoid: null

networks:
  selenoid:
    external:
      name: selenoid
